version: '3'

networks:
  msNet:

services:

  config-service:
    image: nosbielc/mixed-salad-config-service:latest
    networks:
    - msNet
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9090"]
      interval: 2s
      timeout: 5s
      retries: 30

  admin-service:
    image: nosbielc/mixed-salad-admin-service:latest
    networks:
      - msNet
    ports:
      - 9094:9094
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      config-service:
        condition: service_healthy

  discovery-service:
    image: nosbielc/mixed-salad-discovery-service:latest
    networks:
      - msNet
    ports:
      - 9091:9091
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
      admin-service:
        condition: service_started

  gateway-service:
    image: nosbielc/mixed-salad-gateway-service:latest
    networks:
      - msNet
    ports:
      - 80:9092
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
      admin-service:
        condition: service_started
      discovery-service:
        condition: service_started

  zipkin-service:
    image: nosbielc/mixed-salad-zipkin-service:latest
    networks:
      - msNet
    ports:
      - 9095:9095
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
      admin-service:
        condition: service_started
      discovery-service:
        condition: service_started
      gateway-service:
        condition: service_started

  auth-service:
    image: nosbielc/mixed-salad-auth-service:latest
    networks:
      - msNet
    ports:
      - 9093:9093
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
      admin-service:
        condition: service_started
      discovery-service:
        condition: service_started
      gateway-service:
        condition: service_started
      zipkin-service:
        condition: service_started

  banco-central-service:
    image: nosbielc/mixed-salad-banco-central-service:latest
    networks:
      - msNet
#    ports:
#      - "8001-8020"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      config-service:
        condition: service_healthy
      admin-service:
        condition: service_started
      discovery-service:
        condition: service_started
      gateway-service:
        condition: service_started
      zipkin-service:
        condition: service_started
      auth-service:
        condition: service_started