version: '3'

networks:
  msNet:

services:

  config-service:
    image: nosbielc/mixed-salad-config-service:latest
    networks:
      - msNet
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
#    healthcheck:
#      test: CMD curl --fail -s http://localhost:9090/actuator/health/ || exit 1
#      #      test: [ "CMD", "curl", "--fail", "-s", "http://localhost:9090/actuator/health || exit 1" ]
#      interval: 1m30s
#      timeout: 10s
#      retries: 300

  admin-service:
    image: nosbielc/mixed-salad-admin-service:latest
    networks:
      - msNet
    ports:
      - 9094:9094
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - config-service

  discovery-service:
    image: nosbielc/mixed-salad-discovery-service:latest
    networks:
      - msNet
    ports:
      - 9091:9091
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - config-service
      - admin-service

  gateway-service:
    image: nosbielc/mixed-salad-gateway-service:latest
    networks:
      - msNet
    ports:
      - 9092:9092
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - config-service
      - admin-service
      - discovery-service

  zipkin-service:
    image: nosbielc/mixed-salad-zipkin-service:latest
    networks:
      - msNet
    ports:
      - 9095:9095
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service

  auth-service:
    image: nosbielc/mixed-salad-auth-service:latest
    networks:
      - msNet
    ports:
      - 9093:9093
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
      - zipkin-service

  banco-central-service:
    image: nosbielc/mixed-salad-banco-central-service:latest
    networks:
      - msNet
    ports:
      - "8001-8020"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
      - zipkin-service
      - auth-service
#    deploy:
#      mode: replicated
#      replicas: 4

  prometheus-service:
    image: prom/prometheus
    networks:
      - msNet
    ports:
      - 7000:9090
    volumes:
      #      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - c:/Games:/etc/prometheus
    environment:
      - config.file=/etc/prometheus/prometheus.yml
    restart: always

  grafana-service:
    image: grafana/grafana
    networks:
      - msNet
    ports:
      - 7001:3000
    restart: always
    depends_on:
      - prometheus-service
    #Veja o link https://grafana.com/dashboards/6756 para saber mais sobre o plugin indicado