version: '3'

networks:
  msNet:

services:

  config-service:
    image: nosbielc/config-service:latest
    networks:
    - msNet
    ports:
      - 9090:9090
    environment:
      - SPRING_PROFILES_ACTIVE=prod,native
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:9090"]
      interval: 2s
      timeout: 5s
      retries: 30

  admin-service:
    image: nosbielc/admin-service:latest
    networks:
      - msNet
    ports:
      - 9094:9094
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      - config-service

  discovery-service:
    image: nosbielc/discovery-service:latest
    networks:
      - msNet
    ports:
      - 9091:9091
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      - config-service
      - admin-service

  gateway-service:
    image: nosbielc/gateway-service:latest
    networks:
      - msNet
    ports:
      - 9092:9092
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      - config-service
      - admin-service
      - discovery-service

  zipkin-service:
    image: nosbielc/zipkin-service:latest
    networks:
      - msNet
    ports:
      - 9095:9095
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service

  auth-service:
    image: nosbielc/auth-service:latest
    networks:
      - msNet
    ports:
      - 9093:9093
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
      - zipkin-service

  banco-central-service:
    image: nosbielc/banco-central-service:latest
    networks:
      - msNet
#    ports:
#      - "8001-8020"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: on-failure
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
      - zipkin-service
      - auth-service