version: '3'
volumes:
  adminData:
  authData:
  bancoCentralData:
  configData:
  discoveryData:
  gatewayData:
networks:
  layerOne:
services:
  config-service:
    image: nosbielc/config-service
    networks:
      - layerOne
    ports:
      - 9090:9090
  admin-service:
    image: nosbielc/admin-service
    networks:
      - layerOne
    ports:
      - 9094:9094
    depends_on:
      - config-service
  discovery-service:
    image: nosbielc/discovery-service
    networks:
      - layerOne
    ports:
      - 9091:9091
    depends_on:
      - config-service
      - admin-service
  gateway-service:
    image: nosbielc/gateway-service
    networks:
      - layerOne
    ports:
      - 9092:9092
    depends_on:
      - config-service
      - admin-service
      - discovery-service
  zipkin-service:
    image: nosbielc/zipkin-service
    networks:
      - layerOne
    ports:
      - 9095:9095
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
  auth-service:
    image: nosbielc/auth-service
    networks:
      - layerOne
    ports:
      - 9093:9093
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
      - zipkin-service
  banco-central-service:
    image: nosbielc/banco-central-service
    networks:
      - layerOne
    ports:
      - 8001:8001
    depends_on:
      - config-service
      - admin-service
      - discovery-service
      - gateway-service
      - zipkin-service
      - auth-service

