eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:9091/eureka/

spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nosbielc/MixedSaladServiceConfig
  application:
    name: config-service
    boot:
      admin:
        client:
          url: http://admin-service:9094/admin
          username: "user"
          password: "password"
  zipkin:
    base-url: http://zipkin-service:9095/
