eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9091/eureka/

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Nosbielc/MixedSaladServiceConfig
    boot:
      admin:
        client:
          url: http://localhost:9094/admin
          username: "user"
          password: "password"
  zipkin:
    base-url: http://localhost:9095/